#!/bin/sh

printf "\033[96m*\033[0m Starting \033[97mgetty\033[0m\n"
exec busybox getty -L tty1 115200 vt100 -l /bin/login
exec busybox getty -L tty2 115200 vt100 -l /bin/login
exec busybox getty -L tty3 115200 vt100 -l /bin/login
exec busybox getty -L tty4 115200 vt100 -l /bin/login
exec busybox getty -L tty5 115200 vt100 -l /bin/login
exec busybox getty -L tty6 115200 vt100 -l /bin/login
exec busybox getty -L tty7 115200 vt100 -l /bin/login
exec busybox getty -L tty8 115200 vt100 -l /bin/login
