#!/bin/sh

some_failed=0

printf "\033[91m*\033[0m \033[97mWelcome to \033[91mRedrose Linux\033[0m\033[97m!\033[0m\n" || some_failed=1

printf "\033[96m*\033[0m \033[97mMounting essential filesystems\n" || some_failed=1

busybox mkdir -p /proc /sys /dev /tmp /run /dev/pts || some_failed=1

busybox mount | busybox grep -q 'on /proc ' || { mount -t proc proc /proc \
    && printf "  /proc mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /proc\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /sys ' || { mount -t sysfs sys /sys \
    && printf "  /sys mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /sys\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /dev ' || { mount -t devtmpfs devtmpfs /dev \
    && printf "  /dev mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /tmp ' || { mount -t tmpfs tmpfs /tmp \
    && printf "  /tmp mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /tmp\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /run ' || { mount -t tmpfs tmpfs /run \
    && printf "  /run mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /run\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /dev/pts ' || { mount -t devpts devpts /dev/pts \
    && printf "  /dev/pts mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev/pts\n"; some_failed=1; }
}

busybox cat /etc/hostname > /proc/sys/kernel/hostname || some_failed=1
printf "\033[92m*\033[0m \033[97mSet hostname\n" || some_failed=1

if [ "$some_failed" -ne 0 ]; then
    printf "\033[91m*\033[0m \033[97mSome parts of the boot process have failed before reaching the /boot/target script.\033[0m\n"
    sleep 2
fi

printf "\033[95m*\033[0m \033[97mFinished all. Running getty.\n\033[0m" || some_failed=1
busybox clear || some_failed=1

sh /boot/target || some_failed=1

if [ "$some_failed" -ne 0 ]; then
    printf "\033[91m*\033[0m \033[97mSome parts of the boot process have failed after reaching the /boot/target script. Starting a shell.\033[0m\n"
    sh
fi

printf "\033[91m*\033[0m \033[97mPowering off in 1 second\n"
busybox sleep 1
busybox poweroff -f
