#!/bin/sh

some_failed=0

printf "\033[91m*\033[0m \033[97mWelcome to \033[91mRedrose Linux\033[0m\033[97m!\033[0m\n" || some_failed=1

printf "\033[96m*\033[0m \033[97mMounting essential filesystems\033[0m\n" || some_failed=1

busybox mkdir -p /proc /sys /dev /tmp /run /dev/pts || some_failed=1

busybox mount | busybox grep -q 'on /proc ' || { mount -t proc proc /proc \
    && printf "  /proc mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /proc\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /sys ' || { mount -t sysfs sys /sys \
    && printf "  /sys mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /sys\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /dev ' || { mount -t devtmpfs devtmpfs /dev \
    && printf "  /dev mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /tmp ' || { mount -t tmpfs tmpfs /tmp \
    && printf "  /tmp mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /tmp\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /run ' || { mount -t tmpfs tmpfs /run \
    && printf "  /run mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /run\n"; some_failed=1; }; }

busybox mount | busybox grep -q 'on /dev/pts ' || { mount -t devpts devpts /dev/pts \
    && printf "  /dev/pts mounted successfully\n" \
    || { printf "\033[91m*\033[0m \033[97mFailed to mount /dev/pts\n"; some_failed=1; }
}

printf "\033[96m*\033[0m Making sure services are executable\n" || some_failed=1
busybox chmod 755 /etc/service/*/* || some_failed=1
printf "\033[96m*\033[0m Starting services\n" || some_failed=1

exec runsvdir -P /etc/service
