#include <stdio.h>
#include <unistd.h>
#include <sys/reboot.h>
#include "tui.c"
#include "backend.c"
#include "postinstgen.c"

// this file is the main file of the installer.
// it exports the other functions from tui.c and
// backend.c. got nothing else to say
//
// was ai used in this file? no

void shutdown_computer() {
    sync(); // flush filesystem buffers
    reboot(RB_POWER_OFF);
}

void error() {
    set_text_color(RED);
    printf("\nInstallation has failed. ");
    set_text_color(RESET);
    printf("Please report the error at our Github Issues: ");
    set_text_color(BLUE);
    printf("https://github.com/redroselinux/redroselinux/issues\n");
    set_text_color(RESET);
    printf("\n");
    enter_continue();
    shutdown_computer();
}

void print_step_header() {
    clear();
    installing_header();
    printf("\n");
    separator();
    printf("\n");
}

int run_installation_step(int (*operation)(char*),
    char* arg,
    const char* step_name,
    int is_destructive) {
        set_text_color(is_destructive ? RED : GREEN);
        printf("* ");
        set_text_color(RESET);
        printf("%s\n", step_name);
        fflush(stdout);

        if (operation(arg) != 0) {
            install_failed();
            error();
            return -1;
        }

        print_step_header();
        return 0;
}

int main() {
    // run checks
    printf("Running checks...\n");
    if (list_dev() == 0) {}

    // show main header
    clear();
    main_header();
    set_text_color(YELLOW);
    printf("Known issue: If you press ENTER during installation, it will likely fail. Please avoid doing so.\n\n");
    set_text_color(RESET);
    enter_continue();

    // localization
    clear();
    char* keyboard = localization_header();
    char* lang = language();
    char* time = timezone();
    enter_continue();

    // disk
    clear();
    char* drive = disk_header();
    if (!(drive[0] == '/' &&
        drive[1] == 'd' &&
        drive[2] == 'e' &&
        drive[3] == 'v' &&
        drive[4] == '/')) {
            char drivefixed[128];
            snprintf(drivefixed, sizeof(drivefixed),
                "/dev/%s", drive
            );
            drive = drivefixed;
    }
    enter_continue();

    // user creation
    clear();
    char* username = user_creation();
    char* userpassword = user_password();
    if (userpassword[0] == '\n' || userpassword[0] == '\0') {
        set_text_color(RED);
        printf("REMEMBER THE DEFAULT PASSWORD ABOVE!\n");
        set_text_color(RESET);
    }

    char* rootpassword = root_password();
    if (rootpassword[0] == '\n' || rootpassword[0] == '\0') {
        set_text_color(RED);
        printf("REMEMBER THE DEFAULT PASSWORD ABOVE!\n");
        set_text_color(RESET);
    }

    char* host_name = hostname();
    char* propiertary = propiertary_enable();
    enter_continue();

    // ask for confirmation
    clear();
    installing_header();
    printf("\n");
    separator();
    printf("\nDestructive operations have a ");
    set_text_color(RED);
    printf("red");
    set_text_color(RESET);
    printf(" asterisk (*) next to them while others have a ");
    set_text_color(BLUE);
    printf("blue");
    set_text_color(RESET);
    printf(" one.\n");
    printf("Installing to %s", drive);
    printf("\nAre you sure? (y/n) [y]: ");

    char confirm[4];
    fgets(confirm, sizeof(confirm), stdin);


    if (confirm[0] == 'y' || confirm[0] == '\n') {
        print_step_header();

        if (run_installation_step(wipe_drive, drive, "Preparing the drive!", 1) < 0) return 0;
        if (run_installation_step(iso_to_img, 0, "Converting to .img!", 0 < 0)) return 0;
        if (run_installation_step(dd_drive, drive, "Writing ISO to drive!", 1) < 0) return 0;
        if (run_installation_step(drive_patch, drive, "Patching GRUB config!", 0) < 0) return 0;

        print_step_header();
        if (gen_postinst_scripts(drive, username, userpassword, rootpassword, host_name) != 0) {
            install_failed();
            error();
        }
        else {
            print_step_header();
        }
    }
    installed_header();
    printf("Now, we will reboot the computer and run some post-installation scripts. These scripts are autogenerated and will set up your system based on your preferences.\n");
    printf("After the system powers off, turn it on after removing the installation media.\n\n");
    printf("Please report errors at our Github Issues: ");
    set_text_color(BLUE);
    printf("https://github.com/redroselinux/redroselinux/issues\n\n");
    set_text_color(RESET);
    separator();
    printf("\n");
    enter_continue();
    // finish and shutdown
    shutdown_computer();

    return 0;
}
