#!/bin/sh

printf "\033[96m*\033[0m \033[97mSeeding kernel randomness\n"

if [ -f /var/lib/random-seed ]; then
    cat /var/lib/random-seed > /dev/urandom \
        && printf "  Previous seed loaded\n" \
        || printf "\033[91m*\033[0m \033[97mFailed to load previous seed\n"
else
    printf "  No previous seed found\n"
fi

dd if=/dev/urandom of=/var/lib/random-seed bs=512 count=1 2>/dev/null \
    && printf "  New seed saved\n" \
    || printf "\033[91m*\033[0m \033[97mFailed to save new seed\n"

exec sleep infinity
