#!/bin/sh


if [ -f /var/lib/random-seed ]; then
    cat /var/lib/random-seed > /dev/urandom
fi

dd if=/dev/urandom of=/var/lib/random-seed bs=512 count=1 2>&1 \
    || printf "\033[91m*\033[0m \033[97mFailed to save new seed\n"

exec sleep infinity
