#!/bin/sh

exec </dev/tty1 >/dev/tty1 2>&1
printf "\033[96m*\033[0m Starting \033[97mgetty\033[0m\n"
printf "\n\e[1;92mWelcome\e[0m to Redrose Linux!"

exec busybox getty -L tty1 115200 vt100 -l /bin/login
