name: Python lint (redrose-launcher)

on:
  push:
    paths:
      - "src/redrose-launcher/**/*.py"
      - ".github/workflows/pylint.yml"
  pull_request:
    paths:
      - "src/redrose-launcher/**/*.py"
      - ".github/workflows/lint.yml"

jobs:
  check-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes

      - name: Check for Python errors
        run: |
          pyflakes src/redrose-launcher
